#define _boolean 1
#define _break 2
#define _class 3
#define _double 4
#define _else 5
#define _extends 6
#define _for 7
#define _if 8
#define _implements 9
#define _int 10
#define _interface 11
#define _new 12
#define _newarray 13
#define _null 14
#define _println 15
#define _readln 16
#define _return 17
#define _string 18
#define _void 19
#define _while 20
#define _plus 21
#define _minus 22
#define _multiplication 23
#define _division 24
#define _mod 25
#define _less 26
#define _lessequal 27
#define _greater 28
#define _greaterequal 29
#define _equal 30
#define _notequal 31
#define _and 32
#define _or 33
#define _not 34
#define _assignop 35
#define _semicolon 36
#define _comma 37
#define _period 38
#define _leftparen 39
#define _rightparen 40
#define _leftbracket 41
#define _rightbracket 42
#define _leftbrace 43
#define _rightbrace 44
#define _intconstant 45
#define _doubleconstant 46
#define _stringconstant 47
#define _booleanconstant 48
#define _id 49
